### ISSUE TITLE
python 3 compatibility

### ISSUE THREAD

**Issue by Roguelazer** [20c/pybird#14]
This library doesn't seem to work on Python 3 at all; it looks like it freely intermingles str and bytes.

Are there any plans to port it to python 3?

**Comment by grizz** [comment]
Not currently, this was an inherited project that we don't use anymore. Patches welcome of course, thanks for your PR. :)

doing `2to3`, `pyupgrade`, `black` on it might do the trick.

**Comment by grizz** [comment]
Oh, sure.
