### ISSUE TITLE
Support BIRD 2

### ISSUE THREAD

**Issue by moridius** [20c/pybird#20]
Calling get_peer_status() on BIRD 2 throws exceptions in parsing.

I did this:
```
#!/usr/bin/env python3
import pybird
pybird.PyBird(socket_file="/var/run/bird/bird.ctl").get_peer_status()
```

This throws a ValueError in [line 516](https://github.com/20c/pybird/blob/master/pybird/__init__.py#L516) and an IndexError in [line 523](https://github.com/20c/pybird/blob/master/pybird/__init__.py#L523).

Doesn't pybird support BIRD 2 yet?

**Comment by mkomon** [comment]
BIRD2 up to 2.0.7 is supported since 1.1.2 (my patch, already merged), versions 2.0.8 and newer are supported in 1.1.3 (currently PR #26).
