### ISSUE TITLE
Feature request: Web server

### ISSUE THREAD

**Issue by martzuk** [20c/pybird#3]
It would be cool to perhaps implement a simple web server to serve as an API, for example using CherryPy.

**Comment by martzuk** [comment]
After quickly playing around I guess this is pretty easy to implement separately, using Pybird as a library.

**Comment by grizz** [comment]
I like the idea -- I think you're probably right that it would be better implemented separately. Would like to see whatever you come up with if you don't mind showing it.

**Comment by martzuk** [comment]
So far it's as simple as
```
import cherrypy
import json
from pybird import PyBird

class PybirdAPI(object):
    pybird = PyBird(socket_file='/run/bird.ctl')

    @cherrypy.expose
    def index(self):
        return "PybirdAPI"

    @cherrypy.expose
    def peer_state(self):
	peer_state = self.pybird.get_peer_status()
        return json.dumps(str(peer_state))

if __name__ == '__main__':
    cherrypy.quickstart(PybirdAPI())
```

**Comment by grizz** [comment]
Oh, awesome, haven't used cherrypy in years and years, forgot how simple it was :) Leaving this open to at least add to a docs or example section, thanks
