### ISSUE TITLE
datetime is returned as datetime rather than string

### ISSUE THREAD

**Issue by martzuk** [20c/pybird#4]
Seems from the documentation that this might be intentional, but it would seem better to return it in the same format as Bird, and allow the user to handle it appropriately.
```
>>> status = pybird.get_bird_status()
>>> print status
{'router_id': u'127.0.0.1', 'last_reconfiguration': datetime.datetime(2017, 3, 9, 10, 27, 58), 'version': u'1.6.3', 'last_reboot': datetime.datetime(2017, 3, 9, 10, 27, 58)}
```

**Comment by grizz** [comment]
For now at least, it almost needs to be a datetime, bird changes the format based both on how long it was up and what version of bird you're connecting to.
