### ISSUE TITLE
Full bgp table stalls get_routes

### ISSUE THREAD

**Issue by martzuk** [20c/pybird#5]
```
>>> from pybird import PyBird
>>> pybird = PyBird(socket_file="/run/bird.ctl")
>>> routes = pybird.get_routes(peer="b4_edge01_xxx01")
```
Returns in 47 seconds from birdc -s /run/birdctl show route protocols b4_edge01_xxx01, however it just sits there endlessly using this function.

For a very small table it seems to work ok, no traceback occurs.

**Comment by grizz** [comment]
@martzuk how many routes are in the table? Or want to email me the output?

**Comment by martzuk** [comment]
600k+

**Comment by mkomon** [comment]
I know this issue is super old but I've submitted a patch to fix it. The performance of reading large output from BIRD was not good and my fix improves it by several orders of magnitude. Let's hope it can be merged soon.

**Comment by grizz** [comment]
Thanks :)
